global:
  scrape_interval: 10s
  evaluation_interval: 5s

rule_files:
  - alert.rules

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "monitoring_alertmanager:9093"

scrape_configs:
  - job_name: prometheus
    scrape_interval: 5s
    static_configs:
         - targets:
             - localhost:9090
    metrics_path: /prometheus/metrics

  - job_name: node
    scrape_interval: 5s
    static_configs:
         - targets: ['monitoring_cadvisor:8080' ]

  - job_name: 'aws-instances'
    ec2_sd_configs:
      - region: sa-east-1
        port: 9100
    relabel_configs:
      - source_labels: [__meta_ec2_tag_Name]
        regex: VR-.*
        action: keep
      - source_labels: [__meta_ec2_tag_Name]
        target_label: instance