version: '3.3'

services:
  grafana:
    image: grafana/grafana:5.2.2
    env_file:
      - grafana.configs
    secrets:
      - gf_pass
    ports:
      - "3000:3000"
    networks:
      - proxy
    volumes:
      - /opt/grafana/data/:/var/lib/grafana
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.port=3000"
        - "traefik.docker.network=proxy"
        - "traefik.frontend.passHostHeader=true"
        - "traefik.frontend.rule=Host:grafana.cloud.vrbeneficios.io"
        - "traefik.backend=grafana"
      placement:
        constraints: [ node.role == worker ]

networks:
  proxy:
    external: true

secrets:
  gf_pass: